Repository Rover656/EnderIO-Rewrite, pull requests merged in 2021-11, with the labels that each got.

#25 Feature/tools
  endercore/src/main/java/com/enderio/core/client/screen/EIOScreen.java
  endercore/src/main/java/com/enderio/core/common/capability/MultiCapabilityProvider.java
  enderio-base/src/generated/resources/.cache/cache
  enderio-base/src/generated/resources/assets/enderio/lang/en_ud.json
  enderio-base/src/generated/resources/assets/enderio/lang/en_us.json
  enderio-base/src/generated/resources/assets/enderio/models/item/coordinate_selector.json
  enderio-base/src/generated/resources/assets/enderio/models/item/location_printout.json
  enderio-base/src/generated/resources/assets/enderio/models/item/yeta_wrench.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.gear/yeta_wrench.json
  enderio-base/src/generated/resources/data/enderio/recipes/yeta_wrench.json
  enderio-base/src/generated/resources/data/forge/tags/items/tools/wrench.json
  enderio-base/src/main/java/com/enderio/base/EnderIO.java
  enderio-base/src/main/java/com/enderio/base/client/ClientSetup.java
  enderio-base/src/main/java/com/enderio/base/client/renderer/GearBEWLR.java
  enderio-base/src/main/java/com/enderio/base/client/renderer/GraveRenderer.java
  enderio-base/src/main/java/com/enderio/base/client/screen/CoordinateMenuScreen.java
  enderio-base/src/main/java/com/enderio/base/common/capability/EIOCapabilities.java
  enderio-base/src/main/java/com/enderio/base/common/capability/location/CoordinateSelection.java
  enderio-base/src/main/java/com/enderio/base/common/capability/location/CoordinateSelectionHolder.java
  enderio-base/src/main/java/com/enderio/base/common/capability/location/ICoordinateSelectionHolder.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/AutoSmeltEnchantment.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/AutoSmeltHandler.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/EIOBaseEnchantment.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/EIOEnchantmentCategories.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/EIOEnchantments.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/RepellentEnchantment.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/ShimmerEnchantment.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/SoulBoundEnchantment.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/SoulBoundHandler.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/WitherArrowEnchantment.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/WitherWeaponEnchantment.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/XPBoostEnchantment.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/XPBoostHandler.java
  enderio-base/src/main/java/com/enderio/base/common/item/EIOItems.java
  enderio-base/src/main/java/com/enderio/base/common/item/LocationPrintoutItem.java
  enderio-base/src/main/java/com/enderio/base/common/item/misc/GearItem.java
  enderio-base/src/main/java/com/enderio/base/common/item/tool/CoordinateSelectorItem.java
  enderio-base/src/main/java/com/enderio/base/common/item/tool/YetaWrenchItem.java
  enderio-base/src/main/java/com/enderio/base/common/lang/EIOLang.java
  enderio-base/src/main/java/com/enderio/base/common/menu/CoordinateMenu.java
  enderio-base/src/main/java/com/enderio/base/common/menu/EIOMenus.java
  enderio-base/src/main/java/com/enderio/base/common/network/ClientToServerMenuPacket.java
  enderio-base/src/main/java/com/enderio/base/common/network/EIOPackets.java
  enderio-base/src/main/java/com/enderio/base/common/network/Packet.java
  enderio-base/src/main/java/com/enderio/base/common/network/packet/UpdateCoordinateSelectionNameMenuPacket.java
  enderio-base/src/main/java/com/enderio/base/common/tag/EIOTags.java
  enderio-base/src/main/java/com/enderio/base/data/recipe/standard/ItemRecipes.java
  enderio-base/src/main/java/com/enderio/base/data/recipe/standard/StandardRecipes.java
Labels: enhancement

#32 Grinding balls recipes
  enderio-base/src/generated/resources/.cache/cache
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.main/conductive_iron_ball.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.main/construction_alloy_ball.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.main/dark_steel_ball.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.main/electrical_steel_ball.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.main/end_steel_ball.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.main/energetic_alloy_ball.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.main/pulsating_iron_ball.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.main/redstone_alloy_ball.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.main/soularium_ball.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.main/vibrant_alloy_ball.json
  enderio-base/src/generated/resources/data/enderio/recipes/conductive_iron_ball.json
  enderio-base/src/generated/resources/data/enderio/recipes/construction_alloy_ball.json
  enderio-base/src/generated/resources/data/enderio/recipes/dark_steel_ball.json
  enderio-base/src/generated/resources/data/enderio/recipes/electrical_steel_ball.json
  enderio-base/src/generated/resources/data/enderio/recipes/end_steel_ball.json
  enderio-base/src/generated/resources/data/enderio/recipes/energetic_alloy_ball.json
  enderio-base/src/generated/resources/data/enderio/recipes/pulsating_iron_ball.json
  enderio-base/src/generated/resources/data/enderio/recipes/redstone_alloy_ball.json
  enderio-base/src/generated/resources/data/enderio/recipes/soularium_ball.json
  enderio-base/src/generated/resources/data/enderio/recipes/vibrant_alloy_ball.json
  enderio-base/src/main/java/com/enderio/base/common/recipe/EIORecipes.java
  enderio-base/src/main/java/com/enderio/base/common/recipe/grindingball/GrindingballRecipe.java
  enderio-base/src/main/java/com/enderio/base/common/recipe/grindingball/IGrindingballRecipe.java
  enderio-base/src/main/java/com/enderio/base/data/recipe/standard/MaterialRecipes.java
Labels: enhancement, work in progress

#35 Config files
  enderio-base/src/main/java/com/enderio/base/EnderIO.java
  enderio-base/src/main/java/com/enderio/base/common/block/DarkSteelLadderHandler.java
  enderio-base/src/main/java/com/enderio/base/common/block/ReinforcedObsidianBlock.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/AutoSmeltEnchantment.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/RepellentEnchantment.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/ShimmerEnchantment.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/SoulBoundEnchantment.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/WitherArrowEnchantment.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/WitherWeaponEnchantment.java
  enderio-base/src/main/java/com/enderio/base/common/enchantment/XPBoostEnchantment.java
  enderio-base/src/main/java/com/enderio/base/common/item/food/EnderiosItem.java
  enderio-base/src/main/java/com/enderio/base/common/item/tool/ElectromagnetItem.java
  enderio-base/src/main/java/com/enderio/base/common/item/tool/LevitationStaffItem.java
  enderio-base/src/main/java/com/enderio/base/common/loot/BrokenSpawnerLootModifier.java
  enderio-base/src/main/java/com/enderio/base/config/base/BaseConfig.java
  enderio-base/src/main/java/com/enderio/base/config/base/client/BaseClientConfig.java
  enderio-base/src/main/java/com/enderio/base/config/base/common/BaseCommonConfig.java
  enderio-base/src/main/java/com/enderio/base/config/base/common/BlocksConfig.java
  enderio-base/src/main/java/com/enderio/base/config/base/common/EnchantmentsConfig.java
  enderio-base/src/main/java/com/enderio/base/config/base/common/ItemsConfig.java
  enderio-base/src/main/java/com/enderio/base/config/decor/DecorConfig.java
  enderio-base/src/main/java/com/enderio/base/config/decor/client/DecorClientConfig.java
  enderio-base/src/main/java/com/enderio/base/config/decor/common/DecorCommonConfig.java
  enderio-base/src/main/java/com/enderio/base/config/machines/MachinesConfig.java
  enderio-base/src/main/java/com/enderio/base/config/machines/client/MachinesClientConfig.java
  enderio-base/src/main/java/com/enderio/base/config/machines/common/MachinesCommonConfig.java
  gradle.properties
Labels: documentation, enhancement, work in progress

#34 Feature/darksteel pickaxe
  endercore/src/main/java/com/enderio/core/common/util/EnergyUtil.java
  enderio-base/src/generated/.gitattributes
  enderio-base/src/generated/resources/.cache/cache
  enderio-base/src/generated/resources/assets/enderio/lang/en_ud.json
  enderio-base/src/generated/resources/assets/enderio/lang/en_us.json
  enderio-base/src/generated/resources/assets/enderio/models/item/dark_steel_axe.json
  enderio-base/src/generated/resources/assets/enderio/models/item/dark_steel_pickaxe.json
  enderio-base/src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_empowered_1.json
  enderio-base/src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_empowered_2.json
  enderio-base/src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_empowered_3.json
  enderio-base/src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_empowered_4.json
  enderio-base/src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_fork.json
  enderio-base/src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_spoon.json
  enderio-base/src/main/java/com/enderio/base/common/capability/EIOCapabilities.java
  enderio-base/src/main/java/com/enderio/base/common/capability/darksteel/DarkSteelUpgradeable.java
  enderio-base/src/main/java/com/enderio/base/common/capability/darksteel/EnergyDelegator.java
  enderio-base/src/main/java/com/enderio/base/common/capability/darksteel/IDarkSteelUpgradable.java
  enderio-base/src/main/java/com/enderio/base/common/capability/darksteel/IDarkSteelUpgrade.java
  enderio-base/src/main/java/com/enderio/base/common/capability/darksteel/package-info.java
  enderio-base/src/main/java/com/enderio/base/common/item/EIOItems.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/DarkSteelAxeItem.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/DarkSteelPickaxeItem.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/IDarkSteelItem.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/package-info.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/upgrades/DarkSteelUpgradeRecipe.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/upgrades/DarkSteelUpgradeRegistry.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/upgrades/EmpoweredUpgrade.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/upgrades/ForkUpgrade.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/upgrades/SpoonUpgrade.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/upgrades/item/DarkSteelUpgradeItem.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/upgrades/package-info.java
  enderio-base/src/main/java/com/enderio/base/common/lang/EIOLang.java
  enderio-base/src/main/java/com/enderio/base/common/tag/EIOTags.java
  enderio-base/src/main/resources/assets/enderio/textures/item/dark_steel_upgrade_empowered_1.png
  enderio-base/src/main/resources/assets/enderio/textures/item/dark_steel_upgrade_empowered_2.png
  enderio-base/src/main/resources/assets/enderio/textures/item/dark_steel_upgrade_empowered_3.png
  enderio-base/src/main/resources/assets/enderio/textures/item/dark_steel_upgrade_empowered_4.png
  enderio-base/src/main/resources/assets/enderio/textures/item/dark_steel_upgrade_fork.png
  enderio-base/src/main/resources/assets/enderio/textures/item/dark_steel_upgrade_spoon.png
  enderio-base/src/main/resources/data/enderio/recipes/darksteel_upgrade.json
Labels: enhancement, needs review

#39 Dark Steel Work
  enderio-base/src/generated/resources/.cache/cache
  enderio-base/src/generated/resources/assets/enderio/lang/en_ud.json
  enderio-base/src/generated/resources/assets/enderio/lang/en_us.json
  enderio-base/src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_blank.json
  enderio-base/src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_direct.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.gear/dark_steel_axe.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.gear/dark_steel_pickaxe.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.gear/dark_steel_upgrade_direct.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.gear/dark_steel_upgrade_empowered_1.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.gear/dark_steel_upgrade_empowered_2.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.gear/dark_steel_upgrade_empowered_3.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.gear/dark_steel_upgrade_empowered_4.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.gear/dark_steel_upgrade_fork.json
  enderio-base/src/generated/resources/data/enderio/advancements/recipes/enderio.gear/dark_steel_upgrade_spoon.json
  enderio-base/src/generated/resources/data/enderio/recipes/dark_steel_axe.json
  enderio-base/src/generated/resources/data/enderio/recipes/dark_steel_pickaxe.json
  enderio-base/src/generated/resources/data/enderio/recipes/dark_steel_upgrade_direct.json
  enderio-base/src/generated/resources/data/enderio/recipes/dark_steel_upgrade_empowered_1.json
  enderio-base/src/generated/resources/data/enderio/recipes/dark_steel_upgrade_empowered_2.json
  enderio-base/src/generated/resources/data/enderio/recipes/dark_steel_upgrade_empowered_3.json
  enderio-base/src/generated/resources/data/enderio/recipes/dark_steel_upgrade_empowered_4.json
  enderio-base/src/generated/resources/data/enderio/recipes/dark_steel_upgrade_fork.json
  enderio-base/src/generated/resources/data/enderio/recipes/dark_steel_upgrade_spoon.json
  enderio-base/src/main/java/com/enderio/base/client/renderer/DarkSteelDurabilityRenderer.java
  enderio-base/src/main/java/com/enderio/base/common/item/EIOItems.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/DarkSteelAxeItem.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/DarkSteelUpgradeItem.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/IDarkSteelItem.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/upgrades/DarkSteelUpgradeRegistry.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/upgrades/direct/DirectUpgrade.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/upgrades/direct/DirectUpgradeLootCondition.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/upgrades/direct/DirectUpgradeLootModifier.java
  enderio-base/src/main/java/com/enderio/base/common/item/darksteel/upgrades/direct/package-info.java
  enderio-base/src/main/java/com/enderio/base/common/lang/EIOLang.java
  enderio-base/src/main/java/com/enderio/base/data/recipe/standard/ItemRecipes.java
  enderio-base/src/main/java/com/enderio/base/mixin/client/EnergyBarMixin.java
  enderio-base/src/main/resources/assets/enderio/textures/item/dark_steel_upgrade_blank.png
  enderio-base/src/main/resources/assets/enderio/textures/item/dark_steel_upgrade_direct.png
  enderio-base/src/main/resources/data/enderio/loot_modifiers/direct_upgrade.json
  enderio-base/src/main/resources/data/forge/loot_modifiers/global_loot_modifiers.json
Labels: enhancement, needs review
